# Generated by Django 5.2.8 on 2025-11-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20),
        ),
    ]
